// Das sind die Segmente im Daten-Objekt, die  duch die Verwendung von relational-pouch entstehen.
export type SegmentType =
  | "addresses"
  | "artists"
  | "artworks"
  | "awards"
  | "calculations"
  | "catalogs"
  | "compilations"
  | "editions"
  | "exhibitions"
  | "genres"
  | "groupsofwork"
  | "notes"
  | "publications"
  | "rentals"
  | "sales"
  | "salerightsofuses"
  | "tags"
  | "whiteboards"
  | ""; // Der ist nur für Module die kein segment verwenden.
